# fly.toml app configuration file generated for v2fly-aussie on 2025-01-08T16:34:07+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'v2fly-aussie'
primary_region = 'syd'

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[[services]]
  protocol = 'tcp'
  internal_port = 443

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 35

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '2m0s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
