# fly.toml app configuration file generated for v2fly-aussie-v2 on 2024-12-23T15:30:47+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'v2fly-aussie-v2'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.tls_options]
    alpn = ['h2', 'http/1.1']
    versions = ['TLSv1.2', 'TLSv1.3']
    default_self_signed = false

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[services]]
  protocol = 'tcp'
  internal_port = 80
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  ports = []

[[services]]
  protocol = 'udp'
  internal_port = 7300

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

    [services.ports.tls_options]
      alpn = ['h2', 'http/1.1']
      versions = ['TLSv1.2', 'TLSv1.3']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
